### ISSUE TITLE
a standalone setObjectAcl function

### ISSUE THREAD

**Issue by chapmandu** [mso-net/lucee-aws#14]
It would be sexy to be able to specify an ACL on an object that may be different from the bucket's policy.

**Comment by SimonHooker** [comment]
No problem

**Comment by SimonHooker** [comment]
It looks like the main headache with this will be fully implementing http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/AccessControlList.html in a friendly way.

Does http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/CannedAccessControlList.html have the sufficient granularity that you'd need?
- Authenticated read
- Bucket owner full control
- Bucket owner read access
- Log delivery write access
- Private
- Public read
- Public read and write

I mean it feels like an AuthenticatedReadWrite is missing there

**Comment by chapmandu** [comment]
That's plenty.  in all honesty, I would probably only use public read, and private.

**Comment by SimonHooker** [comment]
No problem, I'll get that much implemented later on then :)

**Comment by SimonHooker** [comment]
@chapmandu you can now specify the appropriate string as argument acl= to putObject, or alternatively do setObjectAcl( key = ' ...' , acl = = '...' )

Not a perfect solution but it adds a little bit of functionality hey :)

**Comment by chapmandu** [comment]
YES! The acl arg in putObject will be very useful.. probably more so than setObjectAcl..
